const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGGEDOUT: 'USER_LOGGEDOUT',
    FETCH_EVENTS: 'FETCH_EVENTS',
    FETCH_EVENT: 'FETCH_EVENT',
    SET_EVENT: 'SET_EVENT',
    ADD_EVENT: 'ADD_EVENT',
    DELETE_EVENT: 'DELETE_EVENT',
    UPDATE_EVENT: 'UPDATE_EVENT',
    //todos will not be implemented for now
    FETCH_TODOS: 'FETCH_TODOS',
    SET_TODO: 'SET_TODO',
    ADD_TODO: 'ADD_TODO',
    DELETE_TODO: 'DELETE_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
}

export default Constants;